# Generated by Django 5.0.6 on 2024-06-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('registered', 'Registered'), ('student', 'Student'), ('teacher', 'Teacher')], default='registered', max_length=10),
        ),
    ]
