# Generated by Django 5.0.6 on 2024-06-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
