# Generated by Django 5.0.6 on 2024-07-02 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
